server:
  port: 1001
#  port: ${random.int[1024,9999]}

spring:
  redis:
    host: 10.40.7.76
    port: 6379
    password: Fwts#2023
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 20000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.40.7.26:3306/ry-config?autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&serverTimezone=Asia/Shanghai
    username: yuyin
    password: iflytekcti
    druid:
      initialSize: 10
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      keepAlive: true

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath*:mapper/**/*Mapper.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true